# Generated by Django 4.1.7 on 2023-09-26 20:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_title', models.CharField(max_length=255)),
                ('video_description', models.TextField()),
                ('video_file', models.FileField(upload_to='videos/')),
                ('subtitle_file', models.FileField(blank=True, null=True, upload_to='subtitles/')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.CharField(max_length=12)),
                ('end_timestamp', models.CharField(max_length=12)),
                ('subtitle_text', models.TextField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videosync.video')),
            ],
        ),
    ]
