# Generated by Django 4.2.5 on 2023-09-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosync', '0002_video_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='videosthumbnails/'),
        ),
    ]
